FROM node:20-alpine AS builder

WORKDIR /app

# Declarar build args para todas as variáveis VITE_
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_NOCODB_TOKEN
ARG VITE_EVOLUTION_API_TOKEN
ARG VITE_CLOUDINARY_CLOUD_NAME
ARG VITE_CLOUDINARY_UPLOAD_PRESET
ARG VITE_PACTO_AMERICANAS_API_TOKEN
ARG VITE_PACTO_MOGIGUACU_API_TOKEN
ARG VITE_PACTO_ARACATUBA_API_TOKEN
ARG VITE_PACTO_PIRACICABA_API_TOKEN
ARG VITE_PACTO_PRESIDENTE_PRUDENTE_API_TOKEN
ARG VITE_PACTO_SAO_JOAO_API_TOKEN
ARG VITE_PACTO_ARARAS_API_TOKEN
ARG VITE_PACTO_MOGIMIRIM_API_TOKEN
ARG VITE_PACTO_PAULINIA_API_TOKEN
ARG VITE_PACTO_24HORAS_API_TOKEN
ARG VITE_PACTO_SOROCABA_API_TOKEN

# Expor como ENV para o Vite ler durante o build
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_NOCODB_TOKEN=$VITE_NOCODB_TOKEN
ENV VITE_EVOLUTION_API_TOKEN=$VITE_EVOLUTION_API_TOKEN
ENV VITE_CLOUDINARY_CLOUD_NAME=$VITE_CLOUDINARY_CLOUD_NAME
ENV VITE_CLOUDINARY_UPLOAD_PRESET=$VITE_CLOUDINARY_UPLOAD_PRESET
ENV VITE_PACTO_AMERICANAS_API_TOKEN=$VITE_PACTO_AMERICANAS_API_TOKEN
ENV VITE_PACTO_MOGIGUACU_API_TOKEN=$VITE_PACTO_MOGIGUACU_API_TOKEN
ENV VITE_PACTO_ARACATUBA_API_TOKEN=$VITE_PACTO_ARACATUBA_API_TOKEN
ENV VITE_PACTO_PIRACICABA_API_TOKEN=$VITE_PACTO_PIRACICABA_API_TOKEN
ENV VITE_PACTO_PRESIDENTE_PRUDENTE_API_TOKEN=$VITE_PACTO_PRESIDENTE_PRUDENTE_API_TOKEN
ENV VITE_PACTO_SAO_JOAO_API_TOKEN=$VITE_PACTO_SAO_JOAO_API_TOKEN
ENV VITE_PACTO_ARARAS_API_TOKEN=$VITE_PACTO_ARARAS_API_TOKEN
ENV VITE_PACTO_MOGIMIRIM_API_TOKEN=$VITE_PACTO_MOGIMIRIM_API_TOKEN
ENV VITE_PACTO_PAULINIA_API_TOKEN=$VITE_PACTO_PAULINIA_API_TOKEN
ENV VITE_PACTO_24HORAS_API_TOKEN=$VITE_PACTO_24HORAS_API_TOKEN
ENV VITE_PACTO_SOROCABA_API_TOKEN=$VITE_PACTO_SOROCABA_API_TOKEN

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
