// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ymzoxftzdvlojenztnjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inltem94ZnR6ZHZsb2plbnp0bmp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MDQzODEsImV4cCI6MjA3NDA4MDM4MX0.AD-uE2f-MFkptgz4SOvX3q2c4Q_J0O9pUf4bh4M_RZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);